version: "3.3"
services:
    ziti-test:
        image: netfoundry/ziti-tunnel:local
        build:
            context: .
            args:
                ZITI_VERSION: 0.15.2
        volumes:
        - .:/netfoundry
        network_mode: host
        cap_add:
        - NET_ADMIN
        environment:
        - NF_REG_NAME=my-ziti-identity-file
        entrypoint: ["sh", "-c", "while true; do sleep 11; done"]
        #command: bash
    ziti-tproxy:
        image: netfoundry/ziti-tunnel:local
        build:
            context: .
            args:
                ZITI_VERSION: 0.15.2
        volumes:
        - .:/netfoundry
        network_mode: host
        cap_add:
        - NET_ADMIN
        environment:
        - NF_REG_NAME=my-ziti-identity-file
        command: tproxy --resolver udp://127.0.0.123:53 --verbose
    ziti-tun:
        image: netfoundry/ziti-tunnel:local
        build:
            context: .
            args:
                ZITI_VERSION: 0.15.2
        volumes:
        - .:/netfoundry
        network_mode: host
        cap_add:
        - NET_ADMIN
        environment:
        - NF_REG_NAME=my-ziti-identity-file
        command: tun --resolver udp://127.0.0.123:53
        devices:
          - "/dev/net/tun:/dev/net/tun"
    ziti-proxy:
        image: netfoundry/ziti-tunnel:local
        build:
            context: .
            args:
                ZITI_VERSION: 0.15.2
        volumes:
        - .:/netfoundry
        environment:
        - NF_REG_NAME=my-ziti-identity-file
        ports:
        - "8888:8888"
        - "9999:9999"
        command: proxy "my example service":8888 "my other example service":9999
